[constraint] adds PositionConstraint with example
SofaDefrost/SoftRobots pull request #205
Opened 2023-03-22 18:19 UTC by EulalieCoevoet

This PR adds two classes:
- PositionConstraint: this componant allows to impose a displacement to a set of points, using a constraint approach with Lagrange's multipliers. See example `docs/sofapython3/examples/component/constraint/PositionConstraint/PositionConstraint.py`. 
- PositionModel: shared implementation of PositionConstraint and PositionEffector (for inverse resolution).

2023-03-23 10:16 UTC, alxbilger requested changes

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/model/PositionModel.inl
> +    drawPoints(vparams, points, 10.0f, RGBAColor(0.,1.,0.,1.));
```suggestion
    drawPoints(vparams, points, 10.0f, RGBAColor::green());
```

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/model/PositionModel.cpp
> +    vector<Vec3> pointsVec3;
```suggestion
    vector<Vec3> pointsVec3;
    pointsVec3.reserve(points.size());
```

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/model/PositionModel.cpp
I think you can factorize the `drawPoints` method using `DataTypes::getCPos`

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/PositionConstraint.inl
> +                                          "displacement = the contstraint will impose the displacement provided in data value[valueIndex] \n"
```suggestion
                                          "displacement = the constraint will impose the displacement provided in data value[valueIndex] \n"
```

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/PositionConstraint.inl
> +                                          "force = the contstraint will impose the force provided in data value[valueIndex] \n"
```suggestion
                                          "force = the constraint will impose the force provided in data value[valueIndex] \n"
```

2023-03-23 10:16 UTC, alxbilger commented on src/SoftRobots/component/constraint/PositionConstraint.cpp
> +// see: http://www.stroustrup.com/C++11FAQ.html#extern-templates
```suggestion
```

2023-03-23 14:42 UTC, EulalieCoevoet commented on src/SoftRobots/component/constraint/model/PositionModel.inl
> +void PositionModel<DataTypes>::storeResults(vector<double> &delta)
No, here the idea is to allow the component to change the value if needed.

2023-03-29 09:19 UTC, alxbilger requested changes
Only minor changes required, otherwise go to go

2023-04-04 13:17 UTC, EulalieCoevoet commented
Thanks @alxbilger for your review. I think we can merge now.

2023-04-04 13:17 UTC, merged